

// Connect single push-button switch on this pin (to gnd) */

sbit rs=P2^4;
sbit lcden=P2^3;
sbit s1=P2^0;
sbit s2=P2^1;
sbit s3=P2^2;
sbit rd=P2^5;
sbit beep=P3^7;
sbit rec=P3^0;
sbit prec=P3^1;
sbit recordon=P3^2;
sbit showrec=P3^3;




/*------------------------------------------------------------------*-
  ---- END OF FILE -------------------------------------------------
-*------------------------------------------------------------------*/



